wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    code_path: code/sweep.py
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1682700014.148
    t:
      1:
      - 1
      - 5
      - 6
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 6
      - 41
      - 53
      - 55
      3:
      - 23
      4: 3.8.10
      5: 0.13.7
      8:
      - 5
